#!/bin/sh

set -e

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

if [ -x /bin/fbset ]
then
	copy_exec /bin/fbset /bin

	LIBC_SO=$(ldd /bin/fbset | sed -nr 's#.* => (/lib[^ ]*/libc\.so\.[^ ]+).*#\1#p' | head -n 1)
	if [ -n "$LIBC_SO" ]; then
		LIBC_DIR=$(dirname "$LIBC_SO")
		find -L "$LIBC_DIR" -maxdepth 1 -name 'libgcc_s.*' -type f | while read so; do
			copy_exec "$so"
		done
	fi
fi
