PKG_NAME="xwayland-deb"
PKG_VERSION="2ce1a2d15c5605cd314d31ce5a693fc635265ebc"
PKG_SHA256="48adbb6018c515bac2c055beacc256d3279ff42e2a4864e599bfa0401bbef76e"
PKG_SOURCE_DIR="$PKG_NAME-${PKG_VERSION}*"
PKG_SITE="$GITHUB_URL/numbqq/$PKG_NAME"
PKG_URL="$PKG_SITE/archive/$PKG_VERSION.tar.gz"
PKG_ARCH="arm aarch64"
PKG_LICENSE="GPL"
PKG_SHORTDESC="Xwayland"
PKG_SOURCE_NAME="$PKG_NAME-${PKG_VERSION}.tar.gz"
PKG_NEED_BUILD="NO"


make_target() {
	:
}

makeinstall_target() {
	mkdir -p $BUILD_DEBS/$VERSION/$KHADAS_BOARD/${DISTRIBUTION}-${DISTRIB_RELEASE}/${PKG_NAME}
	# Remove old debs
	rm -rf $BUILD_DEBS/$VERSION/$KHADAS_BOARD/${DISTRIBUTION}-${DISTRIB_RELEASE}/${PKG_NAME}/*
	cp ${DISTRIB_RELEASE}/${DISTRIB_ARCH}/*.deb $BUILD_DEBS/$VERSION/$KHADAS_BOARD/${DISTRIBUTION}-${DISTRIB_RELEASE}/${PKG_NAME}
}
