PKG_NAME="xwayland-deb"
PKG_VERSION="5f01223141bafd6a8b3a6f360a3e531a75c5ec27"
PKG_SHA256="1acaac395a7d41fb21137aa0debba68c4f49a33a2e46867b021517ea31a7bf4b"
PKG_SOURCE_DIR="$PKG_NAME-${PKG_VERSION}*"
PKG_SITE="$GITHUB_URL/numbqq/$PKG_NAME"
PKG_URL="$PKG_SITE/archive/$PKG_VERSION.tar.gz"
PKG_ARCH="arm aarch64"
PKG_LICENSE="GPL"
PKG_SHORTDESC="Xwayland"
PKG_SOURCE_NAME="$PKG_NAME-${PKG_VERSION}.tar.gz"
PKG_NEED_BUILD="NO"


make_target() {
	:
}

makeinstall_target() {
	mkdir -p $BUILD_DEBS/$VERSION/$KHADAS_BOARD/${DISTRIBUTION}-${DISTRIB_RELEASE}/${PKG_NAME}
	# Remove old debs
	rm -rf $BUILD_DEBS/$VERSION/$KHADAS_BOARD/${DISTRIBUTION}-${DISTRIB_RELEASE}/${PKG_NAME}/*
	cp ${DISTRIB_RELEASE}/${DISTRIB_ARCH}/*.deb $BUILD_DEBS/$VERSION/$KHADAS_BOARD/${DISTRIBUTION}-${DISTRIB_RELEASE}/${PKG_NAME}
}
