PKG_NAME="mutter-debs"
PKG_VERSION="6c452e2f1299f23792b8f666982219dbd4dc62c3"
PKG_SHA256="34eaa148a742f2055bd713addff58562c8579dd3fde011e01acc37ff1909ce36"
PKG_SOURCE_DIR="$PKG_NAME-${PKG_VERSION}*"
PKG_SITE="$GITHUB_URL/numbqq/$PKG_NAME"
PKG_URL="$PKG_SITE/archive/$PKG_VERSION.tar.gz"
PKG_ARCH="arm aarch64"
PKG_LICENSE="GPL"
PKG_SHORTDESC="Mutter"
PKG_SOURCE_NAME="$PKG_NAME-${PKG_VERSION}.tar.gz"
PKG_NEED_BUILD="NO"


make_target() {
	:
}

makeinstall_target() {
	mkdir -p $BUILD_DEBS/$VERSION/$KHADAS_BOARD/${DISTRIBUTION}-${DISTRIB_RELEASE}/${PKG_NAME}
	# Remove old debs
	rm -rf $BUILD_DEBS/$VERSION/$KHADAS_BOARD/${DISTRIBUTION}-${DISTRIB_RELEASE}/${PKG_NAME}/*
	cp ${DISTRIB_RELEASE}/${DISTRIB_ARCH}/*.deb $BUILD_DEBS/$VERSION/$KHADAS_BOARD/${DISTRIBUTION}-${DISTRIB_RELEASE}/${PKG_NAME}
}
