PKG_NAME="mutter-debs"
PKG_VERSION="fa2d63aea08a2e5b1786799aa10b27828d1b6085"
PKG_SHA256="7156705f6d63f377aeb1163d30da96c95d2ba812f7faddaa009fb5403f642111"
PKG_SOURCE_DIR="$PKG_NAME-${PKG_VERSION}*"
PKG_SITE="$GITHUB_URL/numbqq/$PKG_NAME"
PKG_URL="$PKG_SITE/archive/$PKG_VERSION.tar.gz"
PKG_ARCH="arm aarch64"
PKG_LICENSE="GPL"
PKG_SHORTDESC="Mutter"
PKG_SOURCE_NAME="$PKG_NAME-${PKG_VERSION}.tar.gz"
PKG_NEED_BUILD="NO"


make_target() {
	:
}

makeinstall_target() {
	mkdir -p $BUILD_DEBS/$VERSION/$KHADAS_BOARD/${DISTRIBUTION}-${DISTRIB_RELEASE}/${PKG_NAME}
	# Remove old debs
	rm -rf $BUILD_DEBS/$VERSION/$KHADAS_BOARD/${DISTRIBUTION}-${DISTRIB_RELEASE}/${PKG_NAME}/*
	cp ${DISTRIB_RELEASE}/${DISTRIB_ARCH}/*.deb $BUILD_DEBS/$VERSION/$KHADAS_BOARD/${DISTRIBUTION}-${DISTRIB_RELEASE}/${PKG_NAME}
}
