PKG_NAME="mutter-debs"
PKG_VERSION="61bbbf3c034fa8635dc340e4b9afa401d2d82a13"
PKG_SHA256="4defb430b93e43a6fbe255dc9a790566511842edf71676d2775b566779caafe6"
PKG_SOURCE_DIR="$PKG_NAME-${PKG_VERSION}*"
PKG_SITE="$GITHUB_URL/numbqq/$PKG_NAME"
PKG_URL="$PKG_SITE/archive/$PKG_VERSION.tar.gz"
PKG_ARCH="arm aarch64"
PKG_LICENSE="GPL"
PKG_SHORTDESC="Mutter"
PKG_SOURCE_NAME="$PKG_NAME-${PKG_VERSION}.tar.gz"
PKG_NEED_BUILD="NO"


make_target() {
	:
}

makeinstall_target() {
	mkdir -p $BUILD_DEBS/$VERSION/$KHADAS_BOARD/${DISTRIBUTION}-${DISTRIB_RELEASE}/${PKG_NAME}
	# Remove old debs
	rm -rf $BUILD_DEBS/$VERSION/$KHADAS_BOARD/${DISTRIBUTION}-${DISTRIB_RELEASE}/${PKG_NAME}/*
	cp ${DISTRIB_RELEASE}/${DISTRIB_ARCH}/*.deb $BUILD_DEBS/$VERSION/$KHADAS_BOARD/${DISTRIBUTION}-${DISTRIB_RELEASE}/${PKG_NAME}
}
