PKG_NAME="kodi_rk3399"
PKG_VERSION="39414a82eb79c4f2629a9f06488e7391588495be"
PKG_SHA256="8dd065ea01cc3ec2a2101677d8fa881b24f3ce9148ee74f9b8db507833632120"
PKG_SOURCE_DIR="kodi_rk3399-${PKG_VERSION}*"
PKG_SITE="https://github.com/numbqq/kodi_rk3399"
PKG_URL="https://github.com/numbqq/kodi_rk3399/archive/$PKG_VERSION.tar.gz"
PKG_ARCH="arm64"
PKG_LICENSE="GPL"
PKG_SHORTDESC="Kodi for  RK3399"
PKG_SOURCE_NAME="kodi_rk3399-${PKG_VERSION}.tar.gz"
PKG_NEED_BUILD="NO"

make_target() {
	:
}

makeinstall_target() {
	mkdir -p $BUILD_DEBS/$VERSION/$KHADAS_BOARD/${DISTRIBUTION}-${DISTRIB_RELEASE}/kodi
	# Remove old debs
	rm -rf $BUILD_DEBS/$VERSION/$KHADAS_BOARD/${DISTRIBUTION}-${DISTRIB_RELEASE}/kodi/*
	cp ${DISTRIB_RELEASE}/${DISTRIB_ARCH}/*.deb $BUILD_DEBS/$VERSION/$KHADAS_BOARD/${DISTRIBUTION}-${DISTRIB_RELEASE}/kodi
	cp -r ${DISTRIB_RELEASE}/${DISTRIB_ARCH}/deps $BUILD_DEBS/$VERSION/$KHADAS_BOARD/${DISTRIBUTION}-${DISTRIB_RELEASE}/kodi
	cp -r ${DISTRIB_RELEASE}/${DISTRIB_ARCH}/dev $BUILD_DEBS/$VERSION/$KHADAS_BOARD/${DISTRIBUTION}-${DISTRIB_RELEASE}/kodi
}

